version: '3'
services:
  app:
    container_name: skillreview_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:              # without this volume mapping to the directory of our project, live reloading wont happen
      - .:/usr/src/app
    depends_on:
      - skillreview_postgres
    networks:
      - skillreview

  skillreview_postgres:
    image: postgres:latest
    container_name: skillreview_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - skillreview
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: username@skillreview.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - skillreview_postgres
    ports:
      - "5050:80"
    networks:
      - skillreview
    restart: unless-stopped


volumes:
  api:
  database_postgres:

networks:
  skillreview:
    driver: bridge
